server:
  port: 4082

logging:
  level:
    com:
      hedvig: DEBUG
management:
  security:
    enabled: false

spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: update

  jackson:
    serialization:
      write_dates_as_timestamps: false

amqp:
  hostname: localhost
  exchange:
    state: hedvig-assets-state
    pending: hedvig-assets-pending
  queue:
    state: hadvig-assets-state-queue
    pending: hedvig-assets-queue

