spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        ddl-auto: create

  spring:
    datasource:
      url: jdbc:h2:file:~/memory-tracker-db
      username: sa
      password:
      driver-class-name: org.h2.Driver
