server:
  port: 4082

logging:
  level:
    com:
      hedvig: DEBUG
management:
  security:
    enabled: false

hedvig:
  kafka:
    acks: all
    retries: 3
    bootstrap:
      servers: localhost:9092
      schema:
        registry:
          url: http://localhost:8081

spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
  jackson:
    serialization:
      write_dates_as_timestamps: false
