spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
