spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  datasource:
    url: jdbc:postgresql://localhost:5432/asset-tracker
    username: postgres
    password: iambatman
    platform: POSTGRESQL
